### ISSUE TITLE
not compatible with 5.4

### ISSUE THREAD

**Issue by gitteri** [oseintow/laravel-shopify#1]
The share function is no longer available in the service container.

To update we just have to change line 38 to this:
`$this->app->singleton('shopify', function($app)`

Afterwards everything will work in 5.4

**Comment by oseintow** [comment]
Thanks buddy, I have already done that. i updated the master branch.

**Comment by devcronix** [comment]
still not updated

**Comment by mpixelz** [comment]
Hi,
its not in the master.. can you please merge the latest pull for this fix? :)
much appreciated.
Thanks.
