### ISSUE TITLE
RuntimeException: A facade root has not been set.

### ISSUE THREAD

**Issue by iDub79** [oseintow/laravel-shopify#12]
After a fresh installation of Laravel 5.4.27 and following the instructions in the README.md file for this package, when I try to access the 'install_shop' route, I get a RuntimeException of 'A facade root has not been set.'.

![image](https://user-images.githubusercontent.com/2037973/27205210-c962e964-5272-11e7-8344-49144fde2f60.png)

Also, can you please provide some additional information as to where and when to use the functions verifyRequest() and verifyWebhook()?

Appreciate any help.

**Comment by puneetv05** [comment]
@Ian-Wright1979  You can use dependency injection over facades. 
Like mentioned [here ](https://github.com/oseintow/laravel-shopify#controller-example)
Hope this help :)

**Comment by puneetv05** [comment]
Patch Submitted #15

**Comment by mpixelz** [comment]
Hi,
when can we expect this to be merged? 
much appreciated.
Thanks.

**Comment by puneetv05** [comment]
@mpixelz  I have made 2 pull request,  no response yet since 20days+  :(

**Comment by oseintow** [comment]
Sorry, pull request merge. Been away for a while.
