### ISSUE TITLE
Oauth error invalid_request

### ISSUE THREAD

**Issue by bhargavkaklotara** [oseintow/laravel-shopify#16]
Oauth error invalid_request: The redirect_uri is not whitelisted

![image](https://user-images.githubusercontent.com/18646257/28060234-37e49a38-6644-11e7-9009-91797a48fd1a.png)

**Comment by oseintow** [comment]
Go to your admin backend app > app info > app url and paster your redirect url. sorry for the late response.

**Comment by bhargavkaklotara** [comment]
Thank you...for your attention
