### ISSUE TITLE
process_shopify_data -> process_oauth_result

### ISSUE THREAD

**Issue by JonoHall** [oseintow/laravel-shopify#21]
Hi there, just working my way through your repository and noticed your instructions refer to the following:

`$redirectUrl = "http://mydomain.com/process_shopify_data";`

but then go on to create a route:

`Route::get("process_oauth_result",function(\Illuminate\Http\Request $request)`

suggest changing the $redirectUrl line to:

`$redirectUrl = "http://mydomain.com/process_oauth_result";`

**Comment by oseintow** [comment]
Readme updated
