### ISSUE TITLE
Search Queries

### ISSUE THREAD

**Issue by amandasaffer** [oseintow/laravel-shopify#23]
Does this package not support simple search queries such as `admin/customers/search.json?query=email:emailhere@gmail.com`? Using the package for this query returns a large amount of customers, but when I use the query in Node or in my browser it returns one. What gives?

**Comment by oseintow** [comment]
It works you can try 

```
   $customers = $this->shopify->get("admin/customers/search.json", ["query" => "last_name:Harris"]);
```
