### ISSUE TITLE
Create Script Post Data Format 

### ISSUE THREAD

**Issue by shanisingh03** [oseintow/laravel-shopify#26]
I want To write Script in Shopify Script Tag When Someone installed the app.

Here Is Th Code Which I Used
`Shopify::setShopUrl($shop)->setAccessToken($access_token)->post("admin/script_tags.json", [
  "script_tag"=> [
    "event"=> "onload",
    "src"=> "https://xpressrevolution.in/social_share.js"
  ]
]);`

Please Help In That

**Comment by oseintow** [comment]
What you have should work.
