### ISSUE TITLE
Shopify application proxy signature can not be verified

### ISSUE THREAD

**Issue by tms320c** [oseintow/laravel-shopify#27]
According to Shopify documentation (https://help.shopify.com/api/guides/application-proxies) "Security: Calculate a digital signature" the proxy signature can be verified in the same way as "hmac" in requests.

It the code of `public function verifyRequest($queryParams)` something seems to be missed and the calculation is not done:
`        $hmac = $queryParams['hmac'] ?? '';
        unset($queryParams['signature'], $queryParams['hmac']);
`
and 'signature' does not take part in verification.

**Comment by oseintow** [comment]
I think a new function has to be created to verify `app proxy requests`. Have not worked really worked with application proxies so i can't say much here. A pr can be submitted though.
