### ISSUE TITLE
Response data dropped by makeRequest

### ISSUE THREAD

**Issue by tms320c** [oseintow/laravel-shopify#28]
`makeRequest` does the following:
`return (is_array($responseBody) && (count($responseBody) > 0)) ? array_shift($responseBody) : $responseBody;`

Because of the `array_shift` it drops "scope" from the response from "admin/oauth/access_token", which is
`{
  "access_token": "f85632530bf277ec9ac6f649fc327f17",
   "scope": "write_orders,read_customers"
}`

**Comment by oseintow** [comment]
I don't think the scope is a problem since you define it beforehand and use it in your oauth process.
