### ISSUE TITLE
400 bad on GET request

### ISSUE THREAD

**Issue by hakimihamdan88** [oseintow/laravel-shopify#29]
im having 400 error request when requesting GET endpoint.

it seems Shopify updated their server. see https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/shopify-api-call-returns-a-http-400-error-with-html-from-google-484157

https://github.com/joshrps/laravel-shopify-API-wrapper/issues/31#issuecomment-394216145

**Comment by oseintow** [comment]
Get request works as it should. Get request `body data` as the links talk about are transformed to query string in this package, so you should be fine.
