### ISSUE TITLE
Request: Determine if a request is Authentic

### ISSUE THREAD

**Issue by jonathan-bird** [oseintow/laravel-shopify#3]
Similar to this: https://github.com/nozzlegear/shopifysharp#determine-if-a-request-is-authentic

It'd be great if there was a method to use the decomposed query string to calculate whether the request is an authentic one.

This hmac signature is a hash of all query string parameters and your app's secret key so would be really useful to use in a middleware.

**Comment by oseintow** [comment]
Sure. Will work on it. Thank you.

**Comment by oseintow** [comment]
I have added verifyRequest and verifyWebhook. Please check the read me.
