### ISSUE TITLE
404 GET Request

### ISSUE THREAD

**Issue by kissartisan** [oseintow/laravel-shopify#30]
Can we treat 404 (not found) GET response as an empty string instead of an error?
For example, in my case, I'm using a webhook and find a product to determine if it does exist. Since ShopifyException class always return if error is 400 and above, my webhook tends to fail everytime a product is not existing.

What I would like to get is an empty string rather than returning the ShopifyException class when error 404 triggers.

Is this fair or I am missing something?

Your response is much appreciated.

Thanks, 
Reymark

**Comment by oseintow** [comment]
I don't think returning an empty string or null makes it right, since empty string can mean a success response.
404 can be treated as Bad URI or Missing Resource. So 404 must be handled appropriately. What i can do is to add A `NOT FOUND EXCEPTION`
