### ISSUE TITLE
Can I use it for private apps without oauth authentication?

### ISSUE THREAD

**Issue by jonjonus** [oseintow/laravel-shopify#8]
I apologize if asking here is wrong.

**Comment by jonathan-bird** [comment]
You'd be better off using a different flow. Technically yes but this app would need more code in the library to be able to handle private auth

**Comment by oseintow** [comment]
This package is oauth bound, so you can't use it without oauth.

**Comment by hsleewis** [comment]
I've been using it without oauth for a private app:

I've just added the shop url and the password to the .env file and then this works:
```php
<?php
$products = $this->shopify->setShopUrl(env('SHOPIFY_URL'))->setAccessToken(env('SHOPIFY_PASSWORD'))->get("admin/products.json");
```
